# Generated by Django 2.2.6 on 2021-03-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
            ],
        ),
    ]
